### ISSUE TITLE
To do 

### ISSUE THREAD

**Issue by CodeWithSwastik** [CodeWithSwastik/HungerGamesBot#1]
# To Do 

0. Fix Bugs ✓
1. Battles
2. Different phases in each day

- **Open source it** 

If you want anything else to be added feel free to create an issue or comment below.

**Comment by Div-100** [comment]
Pawg

**Comment by SetItOnZygote** [comment]
![48edefd.gif](https://user-images.githubusercontent.com/70650586/107911344-11721000-6f65-11eb-9cc9-19cfe2cd6dee.gif)

**Comment by NightZan999** [comment]
> # To Do
> 1. Fix Bugs
> 2. Generate days randomly
> 3. Implement weapons
> 4. Battles
> 5. Different phases in each day
> 
> * **Open source it**
> 
> If you want anything else to be added feel free to create an issue or comment below.

I think you should make battles more heroic, currently its literally rps, its literally luck. Theres nothing that's so **strategic about the game.**

What would be good, is maybe make the battles better with areas to hit and shields. Another good thing would be making items like wood and making crafting recipes wherein you can gather resources and make your own weapons. 

Obviously with this much in hand, you'd need some help. You can create an item class and have a function which computes the entire craft recipes.

**Comment by NightZan999** [comment]
@CodeWithSwastik, you might as well add some kits to the game which inherits from a menus class or something like that. You could add kits, like a Knight kit. This would give the user:
* Instant Sword
* Armor
* Horse to ride on which increases mobility
* Tons of damage
Mage Kit:
* Can fly (affect lasts for a temporary time and uses up a lot of food and water)
* Has a wand which does blast damage to **one person only**
* Has a small splash damage attack

You can add more later but this is the base idea. And of course you will let the user choose their own kit.

**Comment by CodeWithSwastik** [comment]
@NightZan999 this is hunger games not some advernture rpg game lmao

**Comment by NightZan999** [comment]
> @NightZan999 this is hunger games not some advernture rpg game lmao

lmao but you could use IdleRPG

**Comment by NightZan999** [comment]
at-least take my first suggestion tho

**Comment by ChocolateEye** [comment]
Awesome

**Comment by NightZan999** [comment]
finish when @CodeWithSwastik

**Comment by NightZan999** [comment]
@CodeWithSwastik finish pls 🥺

**Comment by MrPotato374** [comment]
yea finish pls :(

**Comment by CodeWithSwastik** [comment]
Turns out I'm working on this again lol

**Comment by CodeWithSwastik** [comment]
I'll close this issue cause its old
