### ISSUE TITLE
HungerGames Sus

### ISSUE THREAD

**Issue by SetItOnZygote** [CodeWithSwastik/HungerGamesBot#2]
Swas made the HungerGames sus because it has many bugs and bugs are sus ![1200px-Node.js_logo.svg.png](https://user-images.githubusercontent.com/70650586/107911675-ad038080-6f65-11eb-82f2-3daba5db4367.png) #StickToNodeJS

**Comment by NightZan999** [comment]
> Swas made the HungerGames sus because it has many bugs and bugs are sus ![1200px-Node.js_logo.svg.png](https://user-images.githubusercontent.com/70650586/107911675-ad038080-6f65-11eb-82f2-3daba5db4367.png) #StickToNodeJS
> 
> STOP CLOSING IT SWAS

lmao, nodejs for hg. Wait a minute something ain't right. 
***if you like node so much why don't you make an hg bot yourself.***
PS: I can help, so invite me too :D
